---
name: Dump
on:
  push:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump/
        id: dump
        with:
          enable-context: 'true'
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
