---
name: Release2
on:
  push:
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    run-on: self-hosted
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
