---
name: Release2
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: self-hosted
    env:
      VERSION: ${{ github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install the gh cli
        uses: ksivamuthu/actions-setup-gh-cli@<VERSION>
        with:
          version: 2.69.0
      - run: cargo build --release
      - run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "target/release/foo"
