---
name: Test
on:
  push:
    paths: ['src/*.rs']
  pull_request:
    paths: ['src/*.rs']
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
